### ISSUE TITLE
wps_pbc

### ISSUE THREAD

**Issue by xiaoyu-ebox** [homeworkc/lazycast#10]
Hi homeworkc, Have you tested wps_pbc to connect? I use my android phone for testing, which is always fixed as wps_pin. I want to find a simpler way to connect, and it was a bit of a hassle to type the password every time.

**Comment by homeworkc** [comment]
I remember I have briefly tried that but I didn't succeed. I think what we should implement is the "p2p persistent group" feature so that every device only has to pair one time and Pi will remember the credentials ever since.

**Comment by homeworkc** [comment]
I have just added the persistent group feature. Now we only have to enter the pin once for each source.
