### ISSUE TITLE
No sound on Raspberry Pi 4

### ISSUE THREAD

**Issue by xricht29** [homeworkc/lazycast#108]
I had some problem with running lazycast on my Raspberry 4. Only miracast from android worked, but without sound and PCs couldn't even connect.

I followed Preparation section in https://github.com/homeworkc/lazycast/blob/master/README.md (NetworkManager, libraries, players,...), downgraded wpa_supplicant and followed the steps in https://github.com/homeworkc/lazycast/issues/90. Now I can use miracast with my laptop as well as with my android, but still with no sound. When android is connected, "sound error" is printed in the console (no error for Windows, but no sound as well). I also tried to use it with sound_output_select=1 in d2.py (3.5mm jack) but with no success.
By the way, when playing something directly on raspberry via HDMI, sound works.

Tried with Windows 10 and Android 11.

Any ideas? I would appreciate any help.

**Comment by homeworkc** [comment]
It seems that  ``sound_output_select`` should be ``2`` in order for the sound  to work on Raspberry Pi 4.
