### ISSUE TITLE
how do you stop Randomised pin

### ISSUE THREAD

**Issue by Fastpoopoo** [homeworkc/lazycast#18]
Is it possible to set it up so you don't have to type a new pin or no pin at all

**Comment by Fastpoopoo** [comment]
found it you just add the pin you want to the end of line 67 in all.sh

**Comment by Fastpoopoo** [comment]
found it you just add the pin you want to the end of line 67 in all.sh

**Comment by mazzasette** [comment]
Thank , it's work.
