### ISSUE TITLE
Lazycast no audio from dac and no video on screen

### ISSUE THREAD

**Issue by TheBrage** [homeworkc/lazycast#2]
I just set up Lazycast, i installed the requirements and then did git cloned Lazycast and chmodded every thing

**Comment by homeworkc** [comment]
Please let me know what type of sources and receiver are you using. In the mean time, you can try to use player 1 (by modifying d2.py) and see if it works.

**Comment by homeworkc** [comment]
Also, do you see messages like 'm3 success' or 'm6 success' in the console? Was it stuck at any particular stage?

**Comment by homeworkc** [comment]
Does this solve your problem?

**Comment by homeworkc** [comment]
You may also want to try lazycast on a clean installed Raspbian. lazycast should works with the unmodified wpa_supplicant that comes with most of distribution. If the wpa_supplicant is modified, it may run into some trouble controlling the wifi interface.
