### ISSUE TITLE
lazycast with wifi in router mode

### ISSUE THREAD

**Issue by codekoch** [homeworkc/lazycast#20]
Hi, 
I'm very impressed by your project. It's the only miracast solution that works out of the box I've found.
I try to integrate lazycast in my raspberry pi project, which I developped for schools in germany (--> http://mediakit.education). 
But at one point I get stucked....
I use the wlan0 device as a router to give internet acces to students and I want to use lazycast parallel to this network connection.... 
I've seen that lazycast is creating a second wifi-device. And it's obviously possible to use it parralel to an internet connection via wifi, so the wlan device can handle two different network connections.
Do you have any idea how can I solve this problem?

Greetings 
Olaf Koch

**Comment by homeworkc** [comment]
Do you mean that you use wlan0 as wifi hotspot? In that case, [issue 3](https://github.com/homeworkc/lazycast/issues/3) has some discussion on how to achieve this.
