### ISSUE TITLE
implementation on RPI+3b

### ISSUE THREAD

**Issue by speicherspule** [homeworkc/lazycast#23]
Hey, ii'm trying to implement this on last rpi 3b+ and take advantage on 802.11ac and 5ghz that this rpi offers. As far i can understand, i can add on the all.sh file "freq=5" to use 5GHz mode. Is it possible to add dual-band(2.4 and 5ghz) compatibilty? and is it possible to use 802.11ac p2p connection to have a more stable connection and better latency? 

Another question, is it possible to add support to multigestures using UIBC? Is there any document regarding uibc that i can read?

**Comment by homeworkc** [comment]
At first glance, it seems like wifi p2p/wifi direct has yet to support 802.11ac: 
https://www.wi-fi.org/knowledge-center/faq/does-wi-fi-direct-work-on-80211-abgn.
It is certainly possible to support to multigestures and there are multiple ways of implementation. In the [spec](https://www.wi-fi.org/file/wi-fi-display-technical-specification-v21), there are 2 UIBC protocols. One is receiving custom messages defined in the spec. (``/control/control.c`` uses this protocol.) The other is receiving standard HID device descriptors and reports (defined in many USB specs.) (``/control/controlhidc.c`` uses this protocol.) Personally I would recommend using the HID protocol, but some sources (e.g., Windows 8.1) does not support it and it is a bit harder to code.
On the receiver side, you also need some library to capture the multigesture input. libinput seems to be a good candidate. (In fact, I wanted to adopt libinput for the keyborad/mouse capture but I never found the time to do so.)
