### ISSUE TITLE
Buildroot implementation

### ISSUE THREAD

**Issue by jiauka** [homeworkc/lazycast#24]
Do you have or have tried to run lazycast on a buildroot raspberry?

thanks for your work.

**Comment by homeworkc** [comment]
I have not. However, I have tried to run lazycast on [minimal Raspian](https://github.com/homeworkc/lazycast/issues/6). You may need to install additional libraries.

**Comment by jiauka** [comment]
Thanks for your promot reply. I have successful run it on a minimal raspbian, however, I do need to run it on top of a buildroot. I was wondering if it was already done. 

I will try it and come back with the results.
