### ISSUE TITLE
d2.py always open VLC when installed on raspbian-nspawn-64

### ISSUE THREAD

**Issue by win98se** [homeworkc/lazycast#41]
On [raspbian-nspawn-64](https://github.com/sakaki-/raspbian-nspawn-64), the architecture is `aarch64` instead of starting with `armv`.

![image](https://user-images.githubusercontent.com/11819816/67624264-f4419b80-f860-11e9-963f-a2f644a92150.png)

This causes `d2.py` always open VLC instead of other binaries. (Line 194 of `d2.py`)

More information on architecture info on raspbian-nspawn-64 -
![image](https://user-images.githubusercontent.com/11819816/67624294-67e3a880-f861-11e9-9012-f72ec6b57d84.png)

**Comment by win98se** [comment]
In addition, using VLC, there are huge delays.

I changed line 194 of `d2.py` from -
`if (os.uname()[-1][:4] != "armv"):`
to -
`if (os.uname()[-1][:4] != "armv") and (os.uname()[-1] != "aarch64"):`

And it works.

**Comment by homeworkc** [comment]
This should be fixed in the current commit.
