### ISSUE TITLE
Attempting to Start on Pi 3 repeats following error.Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory

### ISSUE THREAD

**Issue by TheEndernaut** [homeworkc/lazycast#43]
Failed to connect to non-global ctrl_ifname: (nil)  error: No such file or directory

I am using ethernet to connect my pi, since the wireless module has broken if that helps.

**Comment by homeworkc** [comment]
``lazycast`` needs to use the wireless module to setup connection and receive the data from source.

**Comment by todo87** [comment]
i have this error too but only when it's started as a service. in rest it works just fine (rpi 3 model B v1.2)
next week i will test it with rpi4
