### ISSUE TITLE
Documentation: not mentioning how to build

### ISSUE THREAD

**Issue by rozos** [homeworkc/lazycast#44]
The documentation does not mention how to build the project. It just says "Make all.sh, d2.py, player.bin, h264.bin, control.bin, and controlhidc.bin executable:"

**Comment by homeworkc** [comment]
This instruction assumes that a user download the compiled binaries from the release page so only making those binaries/scripts executable is enough.
If you want to build the project, follow the instruction in [this](https://github.com/homeworkc/lazycast#compile-from-source) section. After these steps, just go to the lazycast directory and run ``make``.
