### ISSUE TITLE
possible over ethernet?

### ISSUE THREAD

**Issue by joop339** [homeworkc/lazycast#45]

**Comment by joop339** [comment]
i was wondering if this is possible to setup over ethernet. If so how?

**Comment by homeworkc** [comment]
Not at the moment. Microsoft has a extension (to the original spec) called MICE (Miracast over Infrastructure Connection). However, at the moment I have issues making the wifi chip on Pi 3 broadcasting the necessary IE (information elements). Also, even with MICE, the initial device discovery still requires wifi p2p so it cannot be used with only ethernet.

**Comment by homeworkc** [comment]
MICE is implemented.
