### ISSUE TITLE
Android cast screen can't find lazycast

### ISSUE THREAD

**Issue by zvonimirfras** [homeworkc/lazycast#5]
`lazycast` successfully runs on RPi3, says it's ready and displays a pin.

When I go to "Cast screen" on my Android device it just keeps searching for the device and never finds anything.
I tried with 3 different devices, that are able to connect to other sinks.

Not sure what to do next or how to debug it.

**Comment by homeworkc** [comment]
It is a bit complicated in the case of Android. Google seems to drop the native support for Miracast in recent Android (6 and later) in order to promote the Chromecast (which is a very different technology from Miracast). There may be ways to enable Miracast for newer phones but those heavily depend on what device you want to use.

**Comment by zvonimirfras** [comment]
I tried it with a 3rd party (Screen Stream Mirroring) under "Miracast" setting too, it didn't find it.

Is there something I can try to verify that it _is_ actually an Android problem rather than something in my configuration?

**Comment by zvonimirfras** [comment]
It took some fiddling with pi's wifi settings, among other things setting the country in wifi localization settings.

**Comment by rahuls4** [comment]
Hi Zzvonimirfras.. I am also facing the same issue with android device. Were you able to find a solution for the same

**Comment by zvonimirfras** [comment]
Hi @rahuls4,

as I mentioned in the last comment, it was fiddling with pi's wifi settings. Big thing was setting the country in the localization settings. I'm not sure if there are others that affect this, I tried many things.

**Comment by homeworkc** [comment]
@rahuls4 if you are using Raspbian Buster. Try downgrading the wpasupplicant package to the version for Raspbian Stretch. See [this](https://www.reddit.com/r/linux4noobs/comments/c5qila/want_to_downgrade_wpa_supplicant/). I have updated the README and I plan to write detailed instructions and make new releases soon.
