### ISSUE TITLE
Support for Raspberry Pi 3A?

### ISSUE THREAD

**Issue by smoonlee** [homeworkc/lazycast#52]
Have downloaded the repo onto my Rpi 3A but when I try can connect either my laptop or tablet it just say failed to connected.

**Comment by homeworkc** [comment]
Please try downgrading the ``wpa_supplicant`` package.

**Comment by homeworkc** [comment]
Also, a reboot is needed after downgrading the package.

**Comment by smoonlee** [comment]
Hi @homeworkc thanks for the reply, rebuilding my Pi3A and will test it shortly just waiting for some updates to complete.

**Comment by smoonlee** [comment]
so it connects then a couple of seconds later disconnected me

**Comment by smoonlee** [comment]
Ha just managed to get it to connect and show my display then it disconnces again

**Comment by smoonlee** [comment]
tried same image ona 3B+ and doesnt the same with latpop and tablet connects and instantly disconnects

**Comment by homeworkc** [comment]
What is the message after disconnection? Is it ``recv timeout`` or other teardown messages?

**Comment by smoonlee** [comment]
![](https://i.imgur.com/ObxnpmN.jpg)

Not the best image but that's what I get after disconnect

**Comment by homeworkc** [comment]
Can you try using ``player_select = 2``? I think this error has something to do with the encoding of audio streams. (Player 1 accepts AAC while player 2 just uses plain PCM.)

**Comment by smoonlee** [comment]
Sure, I've got some time tomorrow will give it another go, apologies for the delay in replies

**Comment by smoonlee** [comment]
@homeworkc  Do you recommend Raspbian Lite or Desktop for this? Got a new SD Card, unrelated to this initial issue, so thought id do some more testing as a 3A would make an ideal little unit for this

**Comment by homeworkc** [comment]
The image I always used and tested is "Raspbian Buster with desktop" from [here](https://www.raspberrypi.org/downloads/raspbian/). (The 1136MB one.)

**Comment by sibav** [comment]
Did anyone figure this out? Tried to print out the error. Seems Errno 11 Resource temporarily unavailable.
