### ISSUE TITLE
Windows 10 says connected but no visible feed

### ISSUE THREAD

**Issue by Plexind** [homeworkc/lazycast#53]
Hi. When I try and connect my windows 10 laptop to lazy it works perfectly for about 15 seconds before the raspberry pi appears to drop the connection. Windows still thinks it is screen mirroring but the feed is no longer visible on the raspberry pi.

**Comment by homeworkc** [comment]
What is your system and what is the output of the terminal? Also, you could try using NetworkManager instead (follow the instructions [here](https://github.com/homeworkc/lazycast/tree/c5762ec1b34a2d8851d6a723c422b891779ea1a6), except only purge dhcpcd5: ``sudo apt purge dhcpcd5``). I found on some system NetworkManager makes the connection more stable. However, this may break the DNS of the network configuration so try on a different SD card or backup your data.
