### ISSUE TITLE
<--M6---: error

### ISSUE THREAD

**Issue by kevinchen1223** [homeworkc/lazycast#60]
<---M6---
SETUP rtsp://192.168.173.80/wfd1.0/streamid=0 RTSP/1.0
CSeq: 101
Transport: RTP/AVP/UDP;unicast;client_port=1028

-------->

['']
[]
Traceback (most recent call last):
  File "./d2.py", line 178, in <module>
    serverport=serverport[-1]
IndexError: list index out of range

**Comment by homeworkc** [comment]
I would need more debug information to see where the problem originates. You may encounter this error when trying to connect or disconnect a device. You can simply ignore it if you can still establish a connection.
