### ISSUE TITLE
How to achieve: p2p 1:n，I want to connect two Android displays together

### ISSUE THREAD

**Issue by kevinchen1223** [homeworkc/lazycast#62]
Hello, senior.Thank you for your project. It helps me a lot。
There's a problem，
How to connect two Android displays together

**Comment by homeworkc** [comment]
It's an interesting idea and it's not entirely impossible but it would require substantial changes to the codes. I would imagine you can do something like modifying the DHCP setting to assign more IPs and then for each IP launch a separate ``d2.py``. There are several parameter that are hard-coded in the source code and you might need to modify them. In addition, you need to tell a second device use a port other than 1028, which I am not sure whether a source device can do that.
