### ISSUE TITLE
wpasupplicant 2.4-1 link broken - Win10 not connecting

### ISSUE THREAD

**Issue by Flexcomp-HAJ** [homeworkc/lazycast#70]
Hi,
I set up Lazycast with my RPI 3. As described by others Win10 is not connecting after in inserting the Pin.
I checked the installation guide again and found out, that wpasupplicant downgrade does not work anymore. Has anyone a new link or alternative idea?
Thank you

**Comment by homeworkc** [comment]
I haven't tested this yet but it seems that the package has been updated to: wpasupplicant_2.4-1+deb9u**6**_armhf.deb. You can download it from [here](https://packages.debian.org/stretch/armhf/wpasupplicant/download) or just replace **4** with **6** in the commands.

**Comment by Flexcomp-HAJ** [comment]
This works!
