### ISSUE TITLE
 Don't enter pin code on win10

### ISSUE THREAD

**Issue by xiaoyu-ebox** [homeworkc/lazycast#8]
Hello, thank you very much for this great project.

I'm using my android phone to test that it's OK， occasionally no display on the pi desktop.
But when I use win10 as a source, win10 don't pop the window to enter pin code, but to enter it on the other end(Raspberry Pi).
![default](https://user-images.githubusercontent.com/30222627/48313106-c2550c00-e5f2-11e8-84ef-169d4e55c88d.png)

**Comment by homeworkc** [comment]
What is the version of Windows 10 that you're using? I have not observed such behavior on my machine.

**Comment by xiaoyu-ebox** [comment]
My version of Windows is the Win10_SingleLang_Chinese(Simplified)_x64 (v1803).
![default](https://user-images.githubusercontent.com/30222627/48384934-722b9600-e727-11e8-99b5-c3ea3dd890b1.png)

**Comment by CaptainMegane** [comment]
HI! I'm using Windows 10 Version 1809 Build 17763.437 and have the same issue, that I do not get prompted for the PIN to connect to device.

Even on Android 9 phone there is no such prompt to enter a pin. This software would be very nice to have and use, if it would work without issues ;-)

**Comment by homeworkc** [comment]
It sounds like the problem is on the Pi side. Have you installed any other programs that might mess or interfere with the p2p settings? Can you try running it on a cleanly-installed Rasbian?

**Comment by xiaoyu-ebox** [comment]
I tested it some time ago on win10 1903, and it worked fine
