### ISSUE TITLE
mice.py password

### ISSUE THREAD

**Issue by myxxmikeyxx** [homeworkc/lazycast#89]
Is it possible to setup mice.py to have a password when connecting? If we did this, would that fix the problem with it sometimes asking for a password and having to cancel it till it does not ask for a password?

**Comment by homeworkc** [comment]
It is possible for MICE to use PIN. The details are in the Microsoft standard linked in readme. However, that probably won't fix the problem of asking PIN. Right now the design is that entering PIN or not is used as an indicator whether the system is using WiFi p2p or existing network connections.

**Comment by myxxmikeyxx** [comment]
Gotach. Thank you for the clarification
