### ISSUE TITLE
[Issue] Casts fine for 30s to a minute then screen corruption

### ISSUE THREAD

**Issue by netham45** [homeworkc/lazycast#95]
I'm streaming from a Windows 10 PC to a Raspberry PI client using the 'player.bin' player over MICE. It streams perfectly for 30s to a minute, complains about missing some packets, then the screen and sound are garbled afterwards and it's not playing at the full rate. Is there anything settings-wise I can do to make it reconnect when it gets corrupt or reinitialize the stream? The h.264 streamer doesn't have the corruption issue but it can't play at full speed and slowly falls further and further behind until the stream stops.

I get the same behavior over a p2p connection too.

Using a Raspberry Pi Zero W with lxde on Raspbian Stretch

These are the errors I see when it starts glitching:

[rtp @ 0x176f010] max delay reached. need to consume packet
[rtp @ 0x176f010] RTP: missed 23 packets
[rtp @ 0x176f010] PES packet size mismatch
[rtp @ 0x176f010] max delay reached. need to consume packet
[rtp @ 0x176f010] RTP: missed 99 packets
[rtp @ 0x176f010] PES packet size mismatch
[rtp @ 0x176f010] max delay reached. need to consume packet
[rtp @ 0x176f010] RTP: missed 117 packets

**Comment by homeworkc** [comment]
This should be solved in the latest version. The main culprit is the background WiFi scanning.
